//CREAR LISTA DE NOMBRES
//CREAR LISTA DE PUNTOS
//CREAR LAS LISTAS BASE (BAQUEIRA BERET/FIERBRUNN/YETI EXTREME)
//RECORRER CADA UNA DE LAS LISTAS Y COMPROVAR EL VALOR DE CADA PERSONA Y ORDENAR DE MAYOR A MENOR
//IMPRIMIR POR PANTALLA LA LISTA DE NOMBRES + LISTA DE PUNTOS